---
title: "Untitled"
author: "Jared"
date: "1/29/2020"
output: html_document
---
```{r}
source(file = "functions.R")
library(phyloseq)
library(vegan) 
library(tidyverse)
library(ggplot2)
library(viridis)
```

```{r setup, include=FALSE}
inc.raw.physeq <- readRDS("../data/incubation_physeq_Aug18.RDS")

inc.physeq <- subset_samples(inc.raw.physeq, day %in% c("7",
                                                        "14",
                                                        "21",
                                                        "35",
                                                        "49",
                                                        "97"))

#Rename treatments to more informative titles
data <- data.frame(sample_data(inc.physeq)) %>%
  mutate(treatment = recode(treatment,
                            'Control' = 'Reference',
                            'CompAlfa' = 'Mix')) %>%
  mutate(C_N = C_flash / N_flash, Inorganic_N = NH3 + NO3) %>%
  mutate(TreatmentAndDay = paste(treatment, day))
data$treatment <- relevel(data$treatment, ref = "Reference") 
data$day <- as.numeric(data$day)
rownames(data) <- data$i_id
data[7:15] <- data.frame(lapply(data[7:15], function(x) scale(x))) # zscore for dbRDA
sample_data(inc.physeq) <- data
inc.physeq
```
```{r}
tree <- read_tree("../data/tree.nwk")

# Add the tree file to the phyloseq object
inc_phy <- merge_phyloseq(inc.physeq, tree)
inc <- inc_phy %>%
  filter_taxa(function(x) sum(x) >= 2, T)
inc
#rarecurve(t(otu_table(inc)))
```

```{r}
rare <- inc %>%
  rarefy_even_depth(sample.size = 6000, rngseed = 432432) %>%
  filter_taxa(function(x) sum(x) >= 2, T)
sample_sums(rare)
rm(inc, inc_phy, inc.physeq, inc.raw.physeq, data, tree)
```
```{r}
species <- data.frame(t(otu_table(rare)))
                      
env <- data.frame(sample_data(rare))

env <- env %>%
  select(treatment, day, colnames(env[7:15]))
```
```{r}
dist <- distance(rare, method = "unifrac", weighted = T)
```
```{r}
dbrda.all <- dbrda(dist ~ ., env)

anova(dbrda.all)

adjR2.dbrda <- RsquareAdj(dbrda.all)$adj.r.squared 

db_rda.vasc.0 <- dbrda(dist ~ 1, data = env) 
db_rda.vasc.all <- dbrda(dist ~ ., data = env)

sel.osR2b <- ordiR2step(db_rda.vasc.0, scope = formula(db_rda.vasc.all), R2scope = adjR2.dbrda, direction = 'both', permutations = 999)
sel.osR2b

sel.osR2b$anova

sel.osR2_adjb <- sel.osR2b
sel.osR2_adjb$anova$`Pr(>F)` <- p.adjust(sel.osR2b$anova$`Pr(>F)`, method = 'bonferroni', n = ncol(env))
sel.osR2_adjb$anova
# bonferroni correction is very conservative
```
```{r}
phyord <- ordinate(
  physeq = rare, 
  method = "dbrda",
  distance = dist,
  formula = ~ day + treatment + NO3 + C_N + C_flash
)
class(rare@sam_data$treatment)
class(rare@sam_data$day)
class(rare@sam_data$pH)
veganord <- dbrda(dist ~ day + treatment + NO3 + C_N + C_flash, data = env, add = T)

levels(rare@sam_data$treatment)
levels(rare@sam_data$day)
levels(rare@sam_data$pH)

ordnotrtday <- dbrda(dist ~ NO3 + C_N + C_flash, data = env, add = T)
anova.cca(veganord)
summary(anova.cca(ordnotrtday))

```
```{r}
# CAP plot
cap_plot <- plot_ordination(
  physeq = rare,
  ordination = veganord,
  shape = "treatment",
  axes = c(1,2)
) +
  geom_point(aes(color = as.factor(day)))

# Now add the environmental variables as arrows
#  “sites”, “species”, “wa”, “lc”, “bp”, “cn”, “reg”
arrowmat <- scores(veganord, display = "bp")
arrowmat
# Add labels, make a data.frame
arrowdf <- data.frame(labels = rownames(arrowmat), arrowmat)
arrowdf$labels <- c("Day", "Alfalfa", "Mix", "Compost", "Nitrate", "C:N", "Total C")
# Define the arrow aesthetic mapping
arrow_map <- aes(xend = dbRDA1,
                 yend = dbRDA2,
                 x = 0,
                 y = 0,
                 shape = NULL,
                 color = NULL)

label_map <- aes(x = 1 * dbRDA1,
                 y = 1 * dbRDA2,
                 shape = NULL,
                 color = NULL,
                 label = labels)

arrowhead = arrow(length = unit(0.02, "npc"))

# Make a new graphic
ordination <- cap_plot +
  geom_segment(
    mapping = arrow_map,
    size = .5,
    data = arrowdf, 
    color = "black", 
    arrow = arrowhead
  ) + 
  geom_text(
    mapping = label_map, 
    size = 2.5,  
    data = arrowdf, 
    color = "red",
    show.legend = FALSE
  ) 
ordination
plot <- ordination +
  theme_my() +
  labs(color = "Day") +
  labs(shape = "Treatment") +
  scale_color_viridis(discrete = T) 

ggsave("../Figures/Constrained.tiff", plot = plot, device = "tiff", width = 140, height = 90, units = "mm", dpi = 500)
```

No day or treatment
```{r}
# CAP plot
cap_plot <- plot_ordination(
  physeq = rare,
  ordination = ordnotrtday,
  shape = "treatment",
  axes = c(1,2)
) +
  geom_point(aes(color = as.factor(day)))

# Now add the environmental variables as arrows
#  “sites”, “species”, “wa”, “lc”, “bp”, “cn”, “reg”
arrowmat <- scores(ordnotrtday, display = "bp")
arrowmat
# Add labels, make a data.frame
arrowdf <- data.frame(labels = rownames(arrowmat), arrowmat)

# Define the arrow aesthetic mapping
arrow_map <- aes(xend = dbRDA1,
                 yend = dbRDA2,
                 x = 0,
                 y = 0,
                 shape = NULL,
                 color = NULL,
                 label = labels)

label_map <- aes(x = 1.1 * dbRDA1,
                 y = 1.1 * dbRDA2,
                 shape = NULL,
                 color = NULL,
                 label = labels)

arrowhead = arrow(length = unit(0.02, "npc"))

# Make a new graphic
ordination <- cap_plot +
  geom_segment(
    mapping = arrow_map,
    size = .5,
    data = arrowdf, 
    color = "gray", 
    arrow = arrowhead
  ) + 
  geom_text(
    mapping = label_map, 
    size = 2.5,  
    data = arrowdf, 
    show.legend = FALSE
  ) 
ordination
plot <- ordination +
  theme_my() +
  labs(color = "Day") +
  labs(shape = "Treatment") +
  scale_color_viridis(discrete = T) 

ggsave("../Figures/ConstrainedNotrtday.png", plot = plot, device = "png", width = 140, height = 90, units = "mm", dpi = 500)
```

```{r}
# Can only show 4 varparts
mod <- varpart(dist, ~ day, ~ treatment, ~ NO3, ~ C_N, data = env)
mod

plot(mod, digits = 3, Xnames = c('day', 'treatment', 'NO3', 'C:N ratio'), bg = c('red', 'blue', 'green', 'orange'))
```
```{r}
# day + treatment + NO3 + C_N 
# fractions [a+b+c]:
rda.all <- dbrda(dist ~ day + treatment + NO3 + C_N + C_flash, data = env)
anova(rda.all)
# fractions [a+b]:
rda.day <- dbrda(dist ~ day, data = env)
# fractions [b+c]:
rda.treatment <- dbrda(dist ~ treatment, data = env)
rda.NO3 <- dbrda(dist ~ treatment, data = env)
rda.C_N <- dbrda(dist ~ treatment, data = env)
```
```{r}
d <- as_tibble(sel.osR2_adjb$anova, rownames = "Variable") %>%
  select(Variable, R2.adj) %>%
  mutate(Variation = R2.adj * 100) 

d
e <- cbind(d, Explains = c(d$Variation[1], diff(as.numeric(d$Variation), lag = 1, differences = 1))) %>%
  select(Variable, Explains)
e
b <- rbind(e,c("Unexplained", 100 - colSums(e[,2, drop = F])))
b
b$Variable <- c("Day", "Treatment", "pH", "Nitrate", "C:N", "TOC", "Others", "Unexplained")
b
library("janitor")
b$Explains <- round(as.numeric(b$Explains), digits = 2)
b$Variable <- as.factor(b$Variable)
c <- b %>% adorn_totals("row")
c
write.csv(c, "../data/VarienceTable.csv") 
```

```{r}
kable(b)
```

