---
title: "Relative abundance of phyla in microcosm input ingredients"
output:
  html_document:
    df_print: paged
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    toc: true
    toc_float: true
    number_sections: false
    code_folding: hide
---
```{r setup, messages = F, cache=TRUE}
knitr::opts_knit$set(root.dir = normalizePath("."))
```
```{r Loading libraries, messages = F, echo=FALSE, warning=FALSE, include=FALSE}
library(phyloseq)
library(vegan)
library(tidyverse)
library(viridis)
library(kableExtra)
```
# Relative abundance bar plots for the incubation inputs
```{r Make phyloseq, message=FALSE, echo=FALSE, warning=FALSE, include=FALSE}
# Read in the phyloseq object, raw object from mothur, see code file mothur_to_phyloseq.R
inc.raw.physeq <- readRDS("../data/incubation_physeq_Aug18.RDS")

# We will be characterizing the ammendments and starting soil, exclude all else
inc.inputs <- subset_samples(inc.raw.physeq, treatment %in% c("AlfalfaAmend", 
                                                              "AlfalfaSoil",
                                                              "CompostAmend"))

# remove unused data
rm(inc.raw.physeq)
```
```{r min taxa, messages = F,}
tps = inc.inputs
#Let's check some of the of taxa counts from theses samples
# Minimum sample size
min(taxa_sums(otu_table(tps)))
```
```{r filter taxa, messages = F, echo=FALSE}
# Remove singletons and 0 counts
tps <- filter_taxa(tps, function(x) sum(x) >= 2, T)
min(taxa_sums(otu_table(tps)))
rm(inc.inputs)
```
```{r rarefy, message=FALSE, echo=FALSE, warning=FALSE, include=FALSE}
tps <- rarefy_even_depth(tps, rngseed = 423423423) 
```
```{r ordinate, message=F, echo=F, warning=F}
sample_sums(tps)
physeq.dist <- ordinate(tps, "PCoA", "bray")
p1 <- plot_ordination(tps, physeq.dist, type = "samples", color = "treatment") +
  geom_point(size=2) +
  labs(color = "Input material") +
  scale_color_viridis(discrete = T, option = "viridis", labels = c("Alfalfa", "Soil", "Compost")) + ggplot2::theme_bw()
p1
theme_my <- function(base_size = 7, base_family = "Palatino")
{
  txt <- element_text(size = 6, colour = "black", face = "plain")
  bold_txt <- element_text(size = 7, colour = "black", face = "bold")

  theme_bw(base_size = base_size, base_family = base_family) +
  theme(
    legend.key = element_blank(), 
    strip.background = element_blank(), 

    text = txt, 
    plot.title = txt, 

    axis.title = bold_txt, 
    axis.text = txt,
    axis.text.x = element_text(angle = 25, vjust = 1, hjust = 1),

    legend.title = bold_txt, 
    legend.text = txt) 
}
ggsave("../Figures/Fig_2.tiff", plot = p1 + theme_my(), device = "tiff", width = 90, height = 90, units = "mm", dpi = 500)
```

Samples were resampled at 4022 reads per sample. Samples were significantly different from each other as per `adonis()`.

```{r ordination stats table, messages = F}
#Stats for input.PCoA
dist <- phyloseq::distance(tps, method = "bray")
input.PCoA.stats <- adonis(dist ~ treatment, data = data.frame(sample_data(tps)))
kable(input.PCoA.stats$aov.tab, "html") %>%
    kable_styling()
xtable::xtable(input.PCoA.stats$aov.tab)
```
```{r relative abundance, messages = F}
# Relative Abundance in inputs
# Put phyloseq object into a df with .02% phylum (glomed at phylum level)
RelativeAbundanceDf <- function(physeq) {
  physeq %>% tax_glom(taxrank = "Phylum") %>% 
    transform_sample_counts(function(x) {x/sum(x)}) %>% 
    psmelt() %>% 
    arrange(Phylum)
}


treatment_names <- c(
  "AlfalfaAmend" = "Alfalfa",
  "AlfalfaSoil" = "Soil",
  "CompostAmend" = "Compost")

# Function to plot relative abundance
PlotRelativeAbundance <- function(df) {
  ggplot(df, aes(x = as.factor(Sample), y = Abundance, fill = Phylum)) +
    geom_bar(stat = "identity", color = "black", size = 0.05) +
    theme(axis.title.x = element_blank()) + 
    guides(fill = guide_legend(reverse = TRUE, keywidth = 1, keyheight = 1)) + 
    ylab("Relative abundance") +
    xlab("Input material") +
    scale_fill_viridis_d()
}

tps.merged <- merge_samples(tps, "treatment")
sample_data(tps.merged)$treatment <- levels(sample_data(tps)$treatment)

top5 <- RelativeAbundanceDf(tps.merged) %>%
  select(Sample, Abundance, Phylum) %>%
  group_by(Sample) %>%
  arrange(desc(Abundance)) %>%
  top_n(5, Abundance) %>%
  arrange(Sample, desc(Abundance))
  
kable(top5, "html") %>%
    kable_styling() %>%
    scroll_box(width = "500px", height = "500px")  
```
```{r figure save, message=F}
plot <- PlotRelativeAbundance(top5) +
  scale_x_discrete(labels = treatment_names) 

plot
#ggsave("../Figures/Fig_1.tiff", plot = plot, device = "tiff", width = 90, height = 180, units = "mm", dpi = 500)
```
```{r}
theme_my <- function(base_size = 7, base_family = "Palatino")
{
  txt <- element_text(size = 6, colour = "black", face = "plain")
  bold_txt <- element_text(size = 7, colour = "black", face = "bold")

  theme_bw(base_size = base_size, base_family = base_family) +
  theme(
    legend.key = element_blank(), 
    strip.background = element_blank(), 

    text = txt, 
    plot.title = txt, 

    axis.title = bold_txt, 
    axis.text = txt,
    axis.text.x = element_text(angle = 25, vjust = 1, hjust = 1),

    legend.title = bold_txt, 
    legend.text = txt) 
}
ggsave("../Figures/Fig_1a.tiff", plot = plot + theme_my(), device = "tiff", width = 90, height = 90, units = "mm", dpi = 500)
```

