---
title: "Incubation soil chemical data"
author: "Jared"
date: "12/4/2019"
output: html_document
---
```{r}
library(phyloseq)
library(vegan)
library(tidyverse)
library(nlme)
library(emmeans)
library(ggpubr)
library(agricolae)
library(broom)
library(xtable)
library(viridis)
```

# Characteristics of the starting soil  

Soil for the incubation was collected from organic alfalfa plots, surface cores were collected from all plots and composited into a bulk soil sample. Bulk soil was sieved to 2mm and allowed to air-dry before microcosm construction. 

The characteristics of the starting soil are as follows:
```{r}
inc.raw.physeq <- readRDS("../data/incubation_physeq_Aug18.RDS")

inc.physeq <- subset_samples(inc.raw.physeq, day %in% c("7",
                                                        "14",
                                                        "21",
                                                        "35",
                                                        "49",
                                                        "97"))

inc.inputs <- subset_samples(inc.raw.physeq, treatment %in% c("AlfalfaAmend", 
                                                              "AlfalfaSoil",
                                                              "CompostAmend"))
#Rename treatments to more informative titles
data <- data.frame(sample_data(inc.physeq)) %>%
  mutate(treatment = recode(treatment,
                            'Control' = 'Reference',
                            'CompAlfa' = 'Mix')) %>%
  mutate(C_N = C_flash / N_flash, Inorganic_N = NH3 + NO3) %>%
  mutate(TreatmentAndDay = paste(treatment, day))
data$treatment <- relevel(data$treatment, ref = "Reference") 
data$day <- as.factor(data$day)
rownames(data) <- data$i_id
sample_data(inc.physeq) <- data
sample_data(inc.physeq)$day <- as.factor(sample_data(inc.physeq)$day)
```
```{r}
inc.model.data <- lme(Inorganic_N~treatment * day, random=~1|replication 
                      , data = data
                      , weights = varIdent(form= ~1|day*treatment)
                      , control = lmeControl(opt = "optim", msVerbose = TRUE))

data1 <- summary(inc.model.data)
data1
anova.lme(inc.model.data)
anova(inc.model.data)
anova(summary(inc.model.data))
#xtable(anova(summary(inc.model.data)))

em <- emmeans(inc.model.data, c("day", "treatment"), data = data)
em
sum_em <- summary(em)
sum_em
levels(data$treatment)

class(data$treatment)

data$treatment <- ordered(data$treatment, levels = c("Alfalfa", "Mix", "Compost", "Reference"))
```


```{r}
theme_set(theme_bw())

p <- ggplot(data = data, aes(x = day, y = Inorganic_N)) +
  geom_point(aes(colour = treatment), size = 1) +
  stat_summary(aes(group = treatment), fun.y = mean,  geom = "line", size = .5, colour = "black") +
  
  xlab("Day") +
  ylab("Inorganic Nitrogen") +
  labs(color = "Treatment") +
  facet_wrap(~treatment) + 
  scale_color_viridis(discrete = T, option = "viridis")

theme_my <- function(base_size = 7, base_family = "Palatino")
{
  txt <- element_text(size = 6, colour = "black", face = "plain")
  bold_txt <- element_text(size = 7, colour = "black", face = "bold")

  theme_bw(base_size = base_size, base_family = base_family) +
  theme(
    legend.key = element_blank(), 
    strip.background = element_blank(), 

    text = txt, 
    plot.title = txt, 

    axis.title = bold_txt, 
    axis.text = txt,
    axis.text.x = element_text(angle = 25, vjust = 1, hjust = 1),

    legend.title = bold_txt, 
    legend.text = txt,
    
    strip.text.x = txt) 
}
p + theme_my()
ggsave("../Figures/Fig_3.tiff", plot = p + theme_my(), device = "tiff", width = 90, height = 90, units = "mm", dpi = 500)
```

```{r}
em2 <- emmeans(inc.model.data, c("treatment", "day"), data = data)

lambdas <- list(
  "Alfalfa - Reference" = c(-1, 1, rep(0, 24 - 2))
  , "Mix - Reference" = c(-1, 0, 1, rep(0, 24 - 3))
  , "Compost - Reference" = c(-1, 0, 0, 1, rep(0, 24 - 4))
  , "Alfalfa - Reference" = c(rep(0, 4), -1, 1, rep(0, 24 - 6))
  , "Mix - Reference" = c(rep(0, 4), -1, 0, 1, rep(0, 24 - 7))
  , "Compost - Reference" = c(rep(0, 4), -1, 0, 0, 1, rep(0, 24 - 8))
  , "Alfalfa - Reference" = c(rep(0, 8), -1, 1, rep(0, 24 - 10))
  , "Mix - Reference" = c(rep(0, 8), -1, 0, 1, rep(0, 24 - 11))
  , "Compost - Reference" = c(rep(0, 8), -1, 0, 0, 1, rep(0, 24 - 12))
  , "Alfalfa - Reference" = c(rep(0, 12), -1, 1, rep(0, 24 - 14))
  , "Mix - Reference" = c(rep(0, 12), -1, 0, 1, rep(0, 24 - 15))
  , "Compost - Reference" = c(rep(0, 12), -1, 0, 0, 1, rep(0, 24 - 16))
  , "Alfalfa - Reference" = c(rep(0, 16), -1, 1, rep(0, 24 - 18))
  , "Mix - Reference" = c(rep(0, 16), -1, 0, 1, rep(0, 24 - 19))
  , "Compost - Reference" = c(rep(0, 16), -1, 0, 0, 1, rep(0, 24 - 20))
  , "Alfalfa - Reference" = c(rep(0, 20), -1, 1, rep(0, 24 - 22))
  , "Mix - Reference" = c(rep(0, 20), -1, 0, 1, rep(0, 24 - 23))
  , "Compost - Reference" = c(rep(0, 20), -1, 0, 0, 1)
)

sum_em2 <- summary(contrast(em2, lambdas), infer = c(TRUE, TRUE), adjust = "mvt")

sum_em2$day <- factor(rep(c(7, 14, 21, 35, 49, 97), each = 3))

theme_set(theme_bw())
p <- ggplot(data = sum_em2, aes(x = day, y = estimate)) +
  geom_pointrange(aes(ymin = lower.CL, ymax = upper.CL, group = contrast, colour = contrast), size = 0.7) +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  xlab("Day") +
  ylab(paste('Inorganic nitrogen \n difference from reference')) +
  scale_y_continuous(breaks = seq(-10, 800, 25)) +
  facet_wrap(~contrast) +
  theme(
    axis.title.y=element_text(colour = "black", size = 17, hjust = 0.5, margin=margin(0,12,0,0)),
    axis.title.x=element_text(colour = "black", size = 17),
    axis.text.x=element_text(colour = "black", size=15),
    axis.text.y=element_text(colour = "black", size=15),
    legend.position="none",
    legend.text=element_text(size=12.5),
    legend.key=element_blank(),
    plot.title = element_text(face = "bold"),
    strip.text.x=element_text(size=15)
  )
```
```{r}
source("functions.R")
day_ggboxplot <- function(df){
  ggboxplot(data = df,x = "treatment"
              , y = "Inorganic_N", color = "treatment"
              , legend = "none") +
    ylab("Inorganic Nitrogen") +
    xlab("Treatment") +
    rotate_x_text(angle = 45) +
    ylim(0, max(data$Inorganic_N) + 5) +
    stat_compare_means(aes(label = ..p.signif..), method = "t.test", ref.group = "Reference", paired = TRUE, size = 2) +
    stat_compare_means(method = "anova", label.y = max(data$Inorganic_N), size = 2, position = position_nudge(x = 1, y = 1.5))
}
p <- day_ggboxplot(data) +
  facet_grid(~day) +
  theme(legend.position = "none")
p
ggsave("../Figures/Fig_S3.png", plot = p + theme_my() +
  theme(legend.position = "none"), device = "png", width = 180, height = 90, units = "mm", dpi = 500)
```

